SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/.gitignore, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/.idea/.gitignore, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/.idea/encodings.xml, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/.idea/misc.xml, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/.idea/vcs.xml, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/pom.xml, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/src/main/java/UTN/Main.java, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java, SiroTorres/LaboratorioIV/JavaScript4S/Leccion12Ts/SistemaEstudiantes/src/main/java/UTN/dominio/Estudiante.java
Sistema de estudiantes en Java tercer semestre, listo para continuar en Metodologia de Sistemas
=> Sistema Estudiantes en Java

SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/.gitignore, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/.idea/.gitignore, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/.idea/encodings.xml, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/.idea/misc.xml, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/.idea/uiDesigner.xml, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/.idea/vcs.xml, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/pom.xml, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/src/main/java/UTN/conexion/Conexion.java, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/src/main/java/UTN/datos/EstudianteDAO.java, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/src/main/java/UTN/dominio/Estudiante.java, SiroTorres/MetodologiaEnSistemas/Clase1/Leccion12/SistemaEstudiantes/src/main/java/UTN/presentacion/SistemaEstudiantesApp.java
Aplicación Sistema Estudiantes Parte 3
=> Clase 01 Metodologia de Sistemas

SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/.gitignore, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/.mvn/wrapper/maven-wrapper.properties, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/mvnw, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/mvnw.cmd, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/pom.xml, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/src/main/resources/application.properties, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/src/main/resources/logback-spring.xml, SiroTorres/MetodologiaEnSistemas/Clase 2/ProyectosJava/Lecccion01/estudiantes/src/test/java/utn/estudiantes/EstudiantesApplicationTests.java
Aplicación de Sistema Estudiantes con Spring Boot -> Parte 1
=> Clase 02 Metodologia

SiroTorres/LaboratorioIV/Python/Clase01/.idea/.gitignore, SiroTorres/LaboratorioIV/Python/Clase01/.idea/Clase01.iml, SiroTorres/LaboratorioIV/Python/Clase01/.idea/inspectionProfiles/Project_Default.xml, SiroTorres/LaboratorioIV/Python/Clase01/.idea/inspectionProfiles/profiles_settings.xml, SiroTorres/LaboratorioIV/Python/Clase01/.idea/misc.xml, SiroTorres/LaboratorioIV/Python/Clase01/.idea/modules.xml, SiroTorres/LaboratorioIV/Python/Clase01/.idea/vcs.xml, SiroTorres/LaboratorioIV/Python/Clase01/Sistemas_numeracion.py, SiroTorres/LaboratorioIV/Python/Clase01/tipo_float.py, SiroTorres/LaboratorioIV/Python/Clase01/valores_infinitos.py
Profundizando en Python con Sistemas Numéricos -> Parte 1
=> Clase 2 Lab IV en Python

SiroTorres/LaboratorioIV/Python/Clase01/tipo_bool.py, SiroTorres/LaboratorioIV/Python/Clase01/tipo_nan.py, SiroTorres/LaboratorioIV/Python/Clase01/tipo_str.py
Sistemas Numéricos y String-> Parte 2
=> Clase 03 Python

SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/.gitignore, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/.mvn/wrapper/maven-wrapper.properties, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/mvnw, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/mvnw.cmd, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/pom.xml, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/modelo/Estudiante.java, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/repositorio/EstudianteRepositorio.java, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/servicio/EstudianteServicio.java, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/servicio/IEstudianteServicio.java, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/resources/application.properties, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/main/resources/logback-spring.xml, SiroTorres/MetodologiaEnSistemas/Clase 3/ProyectosJava/Lecccion01/estudiantes/src/test/java/utn/estudiantes/EstudiantesApplicationTests.java
Aplicación de Sistema Estudiantes con Spring Boot -> Parte 2
=> Clase 03 Java Avanzado

SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/.gitignore, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/.mvn/wrapper/maven-wrapper.properties, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/mvnw, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/mvnw.cmd, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/pom.xml, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/modelo/Estudiante.java, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/repositorio/EstudianteRepositorio.java, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/servicio/EstudianteServicio.java, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/java/utn/estudiantes/servicio/IEstudianteServicio.java, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/resources/application.properties, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/main/resources/logback-spring.xml, SiroTorres/MetodologiaEnSistemas/Clase 4/ProyectosJava/Lecccion01/estudiantes/src/test/java/utn/estudiantes/EstudiantesApplicationTests.java
Aplicación de Sistema Estudiantes con Spring Boot -> Parte 3, solucion al archivo corrupto xml
=> Clase 04 Metodología de Sistemas

SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/.gitignore, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/.mvn/wrapper/maven-wrapper.properties, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/mvnw, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/mvnw.cmd, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/pom.xml, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/java/utn/estudiantes/EstudiantesApplication.java, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/java/utn/estudiantes/modelo/Estudiantes2024.java, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/java/utn/estudiantes/repositorio/EstudianteRepositorio.java, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/java/utn/estudiantes/servicio/EstudianteServicio.java, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/java/utn/estudiantes/servicio/IEstudianteServicio.java, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/resources/application.properties, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/main/resources/logback-spring.xml, SiroTorres/MetodologiaEnSistemas/Clase 5/Lecccion01/estudiantes/src/test/java/utn/estudiantes/EstudiantesApplicationTests.java
Aplicación de Sistema Estudiantes con Spring Boot -> Parte 4
=> Clase 05 Metodologia de Sistemas

SiroTorres/LaboratorioIV/Python/Clase01/dar_formato_str.py, SiroTorres/LaboratorioIV/Python/Clase01/f_string.py
Profundizando en String -> Parte 2
=> Clase 06 Lab Python

SiroTorres/MetodologiaEnSistemas/Node/01-Hola-Mundo/app.js
=> Clase 01 de Node

SiroTorres/MetodologiaEnSistemas/Node/01-Hola-Mundo/monohilo.js
Ejecutamos viendo la asincronía de Node.
=> Clase 04 y 05 en Node.

SiroTorres/MetodologiaEnSistemas/Node/01-Hola-Mundo/entorno.js
Variables de entorno y buenas practicas.
=> Clase 06 en Node

SiroTorres/MetodologiaEnSistemas/Java/Clase 7/Leccion03/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.form, SiroTorres/MetodologiaEnSistemas/Java/Clase 7/Leccion03/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
Proyecto Tienda de Libros con SpringBoot y Swing -> Parte 04
=> Clase 09 Java

SiroTorres/MetodologiaEnSistemas/Node/01-Hola-Mundo/entorno.js, SiroTorres/MetodologiaEnSistemas/Node/01-Hola-Mundo/monohilo.js
Herramientas de desarrollo y producción
=> Clase 07 Node. Nodemon y PM2

SiroTorres/MetodologiaEnSistemas/Java/Clase 7/Leccion03/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.form, SiroTorres/MetodologiaEnSistemas/Java/Clase 7/Leccion03/tienda_libros/src/main/java/utn/tienda_libros/vista/LibroFrom.java
Proyecto Tienda de Libros con SpringBoot y Swing -> Parte 05
=> Clase 10 Java

SiroTorres/MetodologiaEnSistemas/Node/02-Fundamentos_node/async/callbackHell.js
=> Clase 09 Node

SiroTorres/MetodologiaEnSistemas/Node/02-Fundamentos_node/async/promises.js
=> Clase 10 Node

AdryBalmaceda/Ecommerce-v10/cart.js, AdryBalmaceda/Ecommerce-v10/server.js
=> 🛒Archivos Ecommerce-v10

SiroTorres/MetodologiaEnSistemas/Node/02-Fundamentos_node/async/asyncAwait.js, SiroTorres/MetodologiaEnSistemas/Node/02-Fundamentos_node/async/promises.js
=> Clase 11 en Node

SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/js/cart.js, SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/js/index.js, SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/media/index.html, SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/media/style.css
=> Clase 02 JavaScript

SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/js/cart.js, SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/js/index.js, SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/media/index.html, SiroTorres/LaboratorioIV/JavaScript4S/e-commerce2024/client/media/style.css
=> Clase 03 JavaScript

SiroTorres/LaboratorioIV/Python/py-project/README.md, SiroTorres/LaboratorioIV/Python/py-project/app/requirements.txt, SiroTorres/LaboratorioIV/Python/py-project/web-server/main.py, SiroTorres/LaboratorioIV/Python/py-project/web-server/requirements.txt, SiroTorres/LaboratorioIV/Python/py-project/web-server/store.py
Python en Entorno Profesional -> Parte 6
=> Clase 11 Python
